// CANONICAL countdown alert data service for RenewalRadar CE. Alerts are generated by a DB trigger.
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Alert, AlertStatus } from '@/lib/db/types';

const ALERT_COLUMNS =
  'id, user_id, license_id, days_before, trigger_on, channel, status, sent_at, created_at, updated_at';

const ALERT_WITH_LICENSE = `${ALERT_COLUMNS}, license:renewalradarce_licenses(id, label, state_code, profession, license_class, renewal_deadline, status)`;

export async function listAlerts(
  supabase: SupabaseClient,
  userId: string,
  options: { from: number; to: number; status?: AlertStatus; licenseId?: string },
): Promise<{ alerts: Alert[]; total: number }> {
  let query = supabase
    .from('renewalradarce_alerts')
    .select(ALERT_WITH_LICENSE, { count: 'exact' })
    .eq('user_id', userId)
    .order('trigger_on', { ascending: true })
    .range(options.from, options.to);
  if (options.status) query = query.eq('status', options.status);
  if (options.licenseId) query = query.eq('license_id', options.licenseId);

  const { data, error, count } = await query;
  if (error) throw new Error(`listAlerts: ${error.message}`);
  return { alerts: (data ?? []) as unknown as Alert[], total: count ?? 0 };
}

export async function setAlertStatus(
  supabase: SupabaseClient,
  userId: string,
  alertId: string,
  status: 'pending' | 'dismissed',
): Promise<Alert | null> {
  const { data, error } = await supabase
    .from('renewalradarce_alerts')
    .update({ status })
    .eq('id', alertId)
    .eq('user_id', userId)
    .select(ALERT_WITH_LICENSE)
    .maybeSingle();
  if (error) throw new Error(`setAlertStatus: ${error.message}`);
  return data ? (data as unknown as Alert) : null;
}
